//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace webLayout_C7_MasterPage_Theme_Skin_Sitemap
{


    public partial class News
    {

        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new webLayout_C7_MasterPage_Theme_Skin_Sitemap.DefaultMasterPage Master
        {
            get
            {
                return ((webLayout_C7_MasterPage_Theme_Skin_Sitemap.DefaultMasterPage)(base.Master));
            }
        }
    }
}
